name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: fuller-inc/actions-aws-assume-role@v1
      with:
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::144968974651:role/s3-githubaction-role-direct-ap-south-1
        role-session-tagging: true

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://s3-github-bucket-direct
